// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bkc_backend.Data;

namespace bkc_backend.Data.Migrations
{
    [DbContext(typeof(BookingCarDbContext))]
    partial class BookingCarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("bkc_backend.Data.Entities.BookingInfor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeBuId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeBuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeLineManagerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeLineManagerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovingDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReasonBooking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturningDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPerson")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BKC_BookingInfor");
                });

            modelBuilder.Entity("bkc_backend.Data.Entities.BookingResult", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookingInforId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovingTripId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturningTripId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BKC_BookingResult");
                });

            modelBuilder.Entity("bkc_backend.Data.Entities.Car", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AvailableSeat")
                        .HasColumnType("int");

                    b.Property<string>("BuId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("TotalSeat")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BKC_Car");
                });

            modelBuilder.Entity("bkc_backend.Data.Entities.Driver", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BKC_Driver");
                });

            modelBuilder.Entity("bkc_backend.Data.Entities.Participant", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeePhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickupLocationId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BKC_Participant");
                });

            modelBuilder.Entity("bkc_backend.Data.Entities.PickupLocation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookingInforId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BKC_PickupLocation");
                });

            modelBuilder.Entity("bkc_backend.Data.Entities.RelatePerson", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BookingInforId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BKC_RelatePerson");
                });

            modelBuilder.Entity("bkc_backend.Data.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BKC_Role");

                    b.HasData(
                        new
                        {
                            Id = "2",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Member"
                        },
                        new
                        {
                            Id = "1",
                            Name = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("bkc_backend.Data.Entities.RoleUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeeBuId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BKC_RoleUser");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            EmployeeBuId = "300000001732966",
                            EmployeeId = "102144",
                            RoleId = "1"
                        },
                        new
                        {
                            Id = "2",
                            EmployeeBuId = "300000001732966",
                            EmployeeId = "104077",
                            RoleId = "3"
                        },
                        new
                        {
                            Id = "3",
                            EmployeeBuId = "300000001732979",
                            EmployeeId = "602748",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("bkc_backend.Data.Entities.Trip", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CarId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovingDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteByAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReturningDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BKC_Trip");
                });
#pragma warning restore 612, 618
        }
    }
}
